#!/usr/bin/env python3
"""Build tracker_summary.md — pre-computed aggregate for skills.

Skills read this 5KB markdown summary instead of the full tracker
(~100KB+). Generated by /refresh after the tracker merge step. Manual
invocation also supported.

Sections:
  - Tracker meta (post count, date range, last refresh)
  - Top 10 alltime + last-30d
  - Hook type distribution + engagement
  - Topic cluster distribution
  - AI-tone signal frequencies
  - Posting cadence (posts per week, time-slot distribution)
  - Word count quartiles
  - Recent topic freshness (last 30d)

Examples:
  python build_tracker_summary.py
  python build_tracker_summary.py --output tracker_summary.md
  python build_tracker_summary.py --tracker /path/to/tracker.json
"""
from __future__ import annotations

import argparse
import json
import sys
from collections import Counter
from datetime import datetime, timedelta, timezone
from pathlib import Path
from statistics import median, quantiles
from typing import Any

SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))
from tracker_query import (  # noqa: E402
    engagement_score,
    post_created_at,
    _ensure_utf8_stdout,
)

DEFAULT_TRACKER = Path("threads_daily_tracker.json")
DEFAULT_OUTPUT = Path("tracker_summary.md")
DEFAULT_ARCHIVE_DIR = Path("archive")


def collect_all_posts(tracker: dict[str, Any], archive_dir: Path) -> list[dict[str, Any]]:
    """Combine tracker.posts + all archive files, dedupe by id."""
    pool = list(tracker.get("posts", []))
    seen = {str(p.get("id")) for p in pool if p.get("id") is not None}
    if archive_dir.exists():
        for arch in sorted(archive_dir.glob("*.json")):
            try:
                with arch.open(encoding="utf-8") as f:
                    data = json.load(f)
                for p in data.get("posts", []):
                    pid = str(p.get("id"))
                    if pid not in seen:
                        pool.append(p)
                        seen.add(pid)
            except Exception as e:
                sys.stderr.write(f"warning: skipping {arch}: {e}\n")
    return pool


def filter_recent(posts: list[dict[str, Any]], days: int) -> list[dict[str, Any]]:
    cutoff = datetime.now(timezone.utc) - timedelta(days=days)
    out = []
    for p in posts:
        dt = post_created_at(p)
        if dt and dt >= cutoff:
            out.append(p)
    return out


def fmt_post_row(p: dict[str, Any]) -> str:
    pid = p.get("id") or "—"
    when = (p.get("created_at") or "")[:10]
    score = engagement_score(p)
    text = (p.get("text") or "").replace("\n", " ").strip()
    if len(text) > 60:
        text = text[:57] + "…"
    topics = p.get("topics") or []
    topic_str = ",".join(topics[:2]) if topics else "—"
    hook = p.get("hook_type") or "—"
    return f"| `{pid}` | {when} | {score} | {hook} | {topic_str} | {text} |"


def section_meta(tracker: dict[str, Any], all_posts: list[dict[str, Any]]) -> list[str]:
    out = ["## Meta"]
    out.append(f"- Account: `{(tracker.get('account') or {}).get('handle', '?')}`")
    out.append(f"- Last refresh: `{tracker.get('last_updated', '?')}`")
    out.append(f"- Last archive run: `{tracker.get('last_archive_run', 'never')}`")
    out.append(f"- Total posts (tracker + archives): **{len(all_posts)}**")
    out.append(f"- Tracker post count: **{len(tracker.get('posts', []))}**")
    dates = sorted([p.get("created_at") for p in all_posts if p.get("created_at")])
    if dates:
        out.append(f"- Date range: `{dates[0][:10]}` → `{dates[-1][:10]}`")
    out.append("")
    return out


def section_top(label: str, posts: list[dict[str, Any]], n: int) -> list[str]:
    out = [f"## Top {n} — {label}"]
    if not posts:
        out.append("_No posts in this window._")
        out.append("")
        return out
    ranked = sorted(posts, key=engagement_score, reverse=True)[:n]
    out.append("| ID | Date | Eng | Hook | Topics | Text |")
    out.append("|----|------|-----|------|--------|------|")
    for p in ranked:
        out.append(fmt_post_row(p))
    out.append("")
    return out


def section_hook_distribution(posts: list[dict[str, Any]]) -> list[str]:
    out = ["## Hook Type Distribution"]
    if not posts:
        out.append("_No posts._")
        out.append("")
        return out
    buckets: dict[str, list[int]] = {}
    for p in posts:
        key = p.get("hook_type") or "unknown"
        buckets.setdefault(key, []).append(engagement_score(p))
    rows = []
    for key, scores in buckets.items():
        avg = sum(scores) / len(scores)
        rows.append((key, len(scores), avg))
    rows.sort(key=lambda r: r[2], reverse=True)
    out.append("| Hook | Count | Avg Eng |")
    out.append("|------|-------|---------|")
    for key, count, avg in rows:
        out.append(f"| {key} | {count} | {avg:.1f} |")
    out.append("")
    return out


def section_topic_distribution(posts: list[dict[str, Any]], top_k: int = 15) -> list[str]:
    out = ["## Topic Cluster Distribution (top 15)"]
    counter: Counter[str] = Counter()
    eng_sum: dict[str, int] = {}
    for p in posts:
        score = engagement_score(p)
        for t in p.get("topics") or []:
            if not t:
                continue
            counter[t] += 1
            eng_sum[t] = eng_sum.get(t, 0) + score
    if not counter:
        out.append("_No tagged topics._")
        out.append("")
        return out
    out.append("| Topic | Count | Avg Eng |")
    out.append("|-------|-------|---------|")
    for topic, count in counter.most_common(top_k):
        avg = eng_sum[topic] / count if count else 0
        out.append(f"| {topic} | {count} | {avg:.1f} |")
    out.append("")
    return out


def section_ai_tone(posts: list[dict[str, Any]]) -> list[str]:
    out = ["## AI-Tone Signal Frequencies"]
    counter: Counter[str] = Counter()
    posts_with_signal = 0
    for p in posts:
        sigs = p.get("psychology_signals") or {}
        flags = sigs.get("ai_tone_flags") if isinstance(sigs, dict) else None
        if isinstance(flags, list) and flags:
            posts_with_signal += 1
            for s in flags:
                if isinstance(s, str):
                    counter[s] += 1
    if not counter:
        out.append("_No AI-tone signals detected in tracker. Either user's posts are clean or signal-tagging not yet populated._")
        out.append("")
        return out
    out.append(f"Posts flagged: **{posts_with_signal}** of {len(posts)} ({posts_with_signal*100/len(posts):.1f}%)")
    out.append("")
    out.append("| Signal | Count |")
    out.append("|--------|-------|")
    for sig, count in counter.most_common():
        out.append(f"| {sig} | {count} |")
    out.append("")
    return out


def section_cadence(posts: list[dict[str, Any]]) -> list[str]:
    out = ["## Posting Cadence"]
    if not posts:
        out.append("_No posts._")
        out.append("")
        return out
    dates = sorted([post_created_at(p) for p in posts if post_created_at(p)])
    if not dates:
        out.append("_No dated posts._")
        out.append("")
        return out
    span_days = (dates[-1] - dates[0]).days or 1
    posts_per_week = len(posts) * 7.0 / span_days
    out.append(f"- Posts: **{len(posts)}** over {span_days} days")
    out.append(f"- Cadence: **~{posts_per_week:.1f} posts/week**")
    slot_counter: Counter[str] = Counter()
    for p in posts:
        slot_counter[p.get("posting_time_slot") or "unknown"] += 1
    out.append("")
    out.append("**Time-slot distribution:**")
    out.append("")
    out.append("| Slot | Count |")
    out.append("|------|-------|")
    for slot, count in slot_counter.most_common():
        out.append(f"| {slot} | {count} |")
    out.append("")
    return out


def section_word_count(posts: list[dict[str, Any]]) -> list[str]:
    out = ["## Word Count Distribution"]
    counts = [int(p.get("word_count") or 0) for p in posts if p.get("word_count")]
    if not counts:
        out.append("_No word_count tagged in tracker._")
        out.append("")
        return out
    counts.sort()
    out.append(f"- Median: **{int(median(counts))}** words")
    if len(counts) >= 4:
        q = quantiles(counts, n=4)
        out.append(f"- P25 / P75: **{int(q[0])} / {int(q[2])}**")
    out.append(f"- Min / Max: {counts[0]} / {counts[-1]}")
    out.append("")
    return out


def section_recent_freshness(posts: list[dict[str, Any]], days: int = 30) -> list[str]:
    out = [f"## Recent Topic Freshness (last {days}d)"]
    recent = filter_recent(posts, days)
    if not recent:
        out.append("_No posts in window._")
        out.append("")
        return out
    counter: Counter[str] = Counter()
    for p in recent:
        for t in p.get("topics") or []:
            if t:
                counter[t] += 1
    out.append(f"- Posts in window: **{len(recent)}**")
    out.append("")
    if counter:
        out.append("**Topic frequency in window:**")
        out.append("")
        out.append("| Topic | Count |")
        out.append("|-------|-------|")
        for topic, count in counter.most_common(10):
            out.append(f"| {topic} | {count} |")
    else:
        out.append("_No tagged topics in window._")
    out.append("")
    return out


def build_summary(
    tracker_path: Path,
    archive_dir: Path,
) -> str:
    if not tracker_path.exists():
        sys.stderr.write(f"tracker not found at {tracker_path}\n")
        sys.exit(2)
    with tracker_path.open(encoding="utf-8") as f:
        tracker = json.load(f)
    all_posts = collect_all_posts(tracker, archive_dir)
    recent_30 = filter_recent(all_posts, 30)

    lines: list[str] = []
    lines.append(f"# Tracker Summary")
    lines.append("")
    lines.append(f"_Generated: {datetime.now(timezone.utc).isoformat()}_  ")
    lines.append(f"_Skills should read this file (5KB) instead of the full tracker (~100KB+)._")
    lines.append("")
    lines.extend(section_meta(tracker, all_posts))
    lines.extend(section_top("alltime (recent + archives)", all_posts, 10))
    lines.extend(section_top("last 30 days", recent_30, 10))
    lines.extend(section_hook_distribution(all_posts))
    lines.extend(section_topic_distribution(all_posts))
    lines.extend(section_ai_tone(all_posts))
    lines.extend(section_cadence(all_posts))
    lines.extend(section_word_count(all_posts))
    lines.extend(section_recent_freshness(all_posts, days=30))
    return "\n".join(lines)


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(prog="build_tracker_summary", description=__doc__)
    p.add_argument("--tracker", type=Path, default=DEFAULT_TRACKER)
    p.add_argument("--archive-dir", type=Path, default=DEFAULT_ARCHIVE_DIR)
    p.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    return p


def main(argv: list[str] | None = None) -> int:
    _ensure_utf8_stdout()
    parser = build_parser()
    args = parser.parse_args(argv)
    summary = build_summary(args.tracker, args.archive_dir)
    args.output.write_text(summary, encoding="utf-8")
    print(json.dumps({
        "wrote": str(args.output),
        "size_bytes": len(summary.encode("utf-8")),
        "size_lines": summary.count("\n") + 1,
    }, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
